### ISSUE TITLE
Null passed to a callee that requires a non-null parameter

### ISSUE THREAD

**Issue by valeriyvan** [rhcpfan/ios-rubik-solver#2]
CubeSolverViewController.mm:437:2: Null passed to a callee that requires a non-null 1st parameter

**Comment by rhcpfan** [comment]
Hello and thanks for pointing out this issue! 

Could you please add more details about how to reproduce this? I'd like to make sure that we are fixing it in the right place 😄 

Thanks a lot, again 👍

**Comment by valeriyvan** [comment]
Open Xcode.
shift-command-B.
Static analyser is our friend!
I fixed this issue in pull request #3.
Issue might never appear in real life. You could help static analyser with proper nullability declarations.
