### ISSUE TITLE
Trouble running the app

### ISSUE THREAD

**Issue by 212433704** [rhcpfan/ios-rubik-solver#4]
I've been trying to get the code to run under XCode8 and after doing the POD install and then building the app I am getting the following error:

ld: library not found for -lPods-RubikSolver-iOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any idea what I am missing here?

**Comment by rhcpfan** [comment]
Hello! Is this still relevant or may I close this issue?
